//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTag
    {
        public int id { get; set; }
        public int ref_id { get; set; }
        public int tag_id { get; set; }
    
        public virtual Reference Reference { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
