//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int gender_id { get; set; }
        public string photo { get; set; }
        public int author_id { get; set; }
        public int military_rank_id { get; set; }
        public System.DateTime add_date { get; set; }
        public string description { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MilitaryRank MilitaryRank { get; set; }
        public virtual User User { get; set; }
    }
}
